DesafioIdealeware/DesafioIdealeware/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DesafioIdealeware.Models
{
    public class Produto
    {
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }
        //[Range(0, decimal., ErrorMessage = "O preço deve ser maior do que zero")]
        [DisplayFormat(DataFormatString = "{0:#,##0.000#}", ApplyFormatInEditMode = true)]
        public decimal Preco { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "A quantidade em estoque não pode ser igual ou menor a zero")]
        public int Estoque { get; set; }
        public string Descricao { get; set; }
    }
}

DesafioIdealeware/DesafioIdealeware/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DesafioIdealeware.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

DesafioIdealeware/DesafioIdealeware/Areas/Admin/Controllers/HomeController.cs
using DesafioIdealeware.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesafioIdealeware.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index(Usuario usuario = null, bool novo = false)
        {
            ViewBag.Title = "Entrar";
            if (usuario == null)
            {
                return View();
            }
            else
            {
                if (novo)
                {
                    ViewBag.Sucesso = "Usuario cadastrado. Utilize seu e-mail e senha para entrar";
                }
                
                return View(usuario);
            }
            
        }


    }
}

DesafioIdealeware/DesafioIdealeware/Areas/Admin/Controllers/ProdutoController.cs
using DesafioIdealeware.Areas.Admin.Filters;
using DesafioIdealeware.DAO;
using DesafioIdealeware.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesafioIdealeware.Areas.Admin.Controllers
{
    [AutorizacaoFilter]
    public class ProdutoController : Controller
    {
        private ProdutoDAO dao;

        public ProdutoController()
        {
            dao = new ProdutoDAO();
        }

        // GET: Admin/Produto
        public ActionResult Index()
        {
            var produtos = dao.ListarTodos();

            ViewBag.Title = "Listar Produtos";

            return View(produtos);
        }
        
        public ActionResult Visualizar(int id, bool alterado = false, bool novo = false)
        {
            Produto produto = dao.ListarPorId(id);
            if (alterado)
            {
                ViewBag.Sucesso = "Produto #" + produto.Id + " alterado com sucesso";
            }

            if (novo)
            {
                ViewBag.Sucesso = "Produto #" + produto.Id + " cadastrado com sucesso";
            }
            
            ViewBag.Title = "Produto: " + produto.Nome;

            return View(produto);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Produto produto)
        {
            dao.Atualizar(produto);
            return RedirectToAction("Visualizar", "Produto", new { id = produto.Id, alterado = true });
        }

        public ActionResult Cadastro()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Novo(Produto produto)
        {
            produto = dao.Salvar(produto);
            return RedirectToAction("Visualizar", "Produto", new { id = produto.Id, novo = true });
        }

        [HttpGet]
        public ActionResult Pesquisa(string nome)
        {
            ViewBag.nome = nome;
            ViewBag.Title = "Pesquisar produtos com nome: " + nome;
            var produtos = dao.ListarPorNome(nome);
            return View(produtos);
        }

        [HttpPost]
        public ActionResult Excluir(int id)
        {
            try
            {
                dao.Excluir(id);
                return Json(true);
            }
            catch (Exception)
            {
                return Json(false);
            }
        }
    }
}

DesafioIdealeware/DesafioIdealeware/Areas/Admin/Controllers/UsuarioController.cs
using DesafioIdealeware.DAO;
using DesafioIdealeware.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesafioIdealeware.Areas.Admin.Controllers
{
    public class UsuarioController : Controller
    {
        private UsuarioDAO dao;

        public UsuarioController()
        {
            dao = new UsuarioDAO();
        }

        public ActionResult Novo(Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                dao.Salvar(usuario);
                
                return RedirectToAction("Index", "Home", new { usuario = usuario, novo = true });
            }
            else
            {
                return RedirectToAction("Index", "Home", new { usuario = usuario });
            }
        }

        [HttpPost]
        public ActionResult Login(string inputEmail, string inputPassword)
        {
            Usuario usuario = dao.Autenticar(inputEmail, inputPassword);
            if (usuario != null)
            {
                Session["logado"] = usuario;
                return RedirectToAction("Index", "Produto");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult Logout()
        {
            Session.Remove("logado");

            return RedirectToAction("Index", "Home");
        }
    }
}

DesafioIdealeware/DesafioIdealeware/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DesafioIdealeware.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

DesafioIdealeware/DesafioIdealeware/Controllers/ProdutoController.cs
using DesafioIdealeware.DAO;
using DesafioIdealeware.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;

namespace DesafioIdealeware.Controllers
{
    [RoutePrefix("Produtos")]
    public class ProdutoController : ApiController
    {
        private ProdutoDAO dao;

        public ProdutoController()
        {
            dao = new ProdutoDAO();
        }

        [Route]
        [HttpGet]
        [ResponseType(typeof(IEnumerable<Produto>))]
        public HttpResponseMessage GetAll()
        {
            try
            {
                IEnumerable<Produto> produtos = dao.ListarTodos();
                return Request.CreateResponse(HttpStatusCode.OK, produtos);

            }
            catch (Exception ex)
            {
                return Request.CreateResponse(HttpStatusCode.InternalServerError, ex.Message);
            }
            

            
        }
    }
}

DesafioIdealeware/DesafioIdealeware/Areas/Admin/Views/Home/Index.cshtml
@{
    @model DesafioIdealeware.Models.Usuario
}

@if (!string.IsNullOrEmpty(ViewBag.Sucesso))
{
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @ViewBag.Sucesso
    </div>
}

<section class="area-usuarios">
    <section class="col-md-4 col-sm-12 area-login">
        @using (Html.BeginForm("Login", "Usuario", FormMethod.Post))
        {
            <h2 class="form-signin-heading">Acessar a Área Administrativa</h2>

            <div class="form-group">
                <label for="inputEmail" class="sr-only">E-mail:</label>
                <input type="email" id="inputEmail" name="inputEmail" class="form-control" placeholder="E-mail" required autofocus />
            </div>

            <div class="form-group">
                <label for="inputPassword" class="sr-only">Senha:</label>
                <input type="password" id="inputPassword" name="inputPassword" class="form-control" placeholder="Senha" required>
            </div>

            <input type="submit" class="btn btn-lg btn-primary btn-block" value="Entrar"t>
        }
            
    </section>

    <section class="col-md-6 col-sm-12 area-novo-usuario">
        @using (Html.BeginForm("Novo", "Usuario", FormMethod.Post))
        {
            <h2>Criar novo usuário</h2>
            @Html.AntiForgeryToken()
            <div class="form-group">
                @Html.LabelFor(u => u.Nome, "Seu nome:")
                @Html.TextBoxFor(u => u.Nome, new { @class = "form-control" })
                @Html.ValidationMessageFor(u => u.Nome)
            </div>
            <div class="form-group">
                @Html.LabelFor(u => u.Email, "Seu e-mail:")
                @Html.TextBoxFor(u => u.Email, new { @class = "form-control", @type = "email" })
                @Html.ValidationMessageFor(u => u.Email)
            </div>
            <div class="form-group">
                @Html.LabelFor(u => u.Password, "Sua senha:")
                @Html.TextBoxFor(u => u.Password, new { @class = "form-control", @type = "password" })
                @Html.ValidationMessageFor(u => u.Password)
            </div>

            <input type="submit" class="btn btn-lg btn-success" value="Cadastrar" />
        }
            
    </section>
</section>

@section Scripts{
    @Scripts.Render("~/bundles/scripts")
}

DesafioIdealeware/DesafioIdealeware/Areas/Admin/Views/Produto/Cadastro.cshtml
@{ 
    @model DesafioIdealeware.Models.Produto
}

<h3 class="text-muted">Cadastrar Novo Produto</h3>

@using (Html.BeginForm("Novo", "Produto", FormMethod.Post))
{
    @Html.Partial("_FormProduto")

    <input type="submit" value="Cadastrar" class="btn btn-success btn-lg" />
}
    
<hr />
@Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary" })

@section Scripts{
    @Scripts.Render("~/bundles/scripts")
}

DesafioIdealeware/DesafioIdealeware/Areas/Admin/Views/Produto/Index.cshtml
@{ 
    @model IList<DesafioIdealeware.Models.Produto>
}

<div>
    <h3 class="text-muted">Todos Produtos Cadastrados</h3>

    @Html.Partial("_FormPesquisa")

    @Html.Partial("_ListaProdutos")

</div>

@section Scripts{
    @Scripts.Render("~/bundles/scripts")
}

DesafioIdealeware/DesafioIdealeware/Areas/Admin/Views/Produto/Pesquisa.cshtml
@{ 
    @model IList<DesafioIdealeware.Models.Produto>
}

<div>
    <h3 class="text-muted">@Model.Count resultados encontrados com o nome <em>@ViewBag.nome</em> </h3>

    @Html.Partial("_FormPesquisa")

    @Html.Partial("_ListaProdutos")

    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary" })

</div>

@section Scripts{
    @Scripts.Render("~/bundles/scripts")
}

DesafioIdealeware/DesafioIdealeware/Areas/Admin/Views/Produto/Visualizar.cshtml
@{
    @model DesafioIdealeware.Models.Produto
}

<h3 class="text-muted">@Model.Nome</h3>

@if (!string.IsNullOrEmpty(ViewBag.Sucesso))
{
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @ViewBag.Sucesso
    </div>
}




@using (Html.BeginForm("Editar", "Produto", FormMethod.Post))
{

    @Html.HiddenFor(model => model.Id)

    @Html.Partial("_FormProduto")


    <input type="submit" value="Editar" class="btn btn-info btn-lg" />
}

<hr />
@Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary" })

@section Scripts{
    @Scripts.Render("~/bundles/scripts")
}

DesafioIdealeware/DesafioIdealeware/Areas/Admin/Views/Shared/_FormPesquisa.cshtml
@using (Html.BeginForm("Pesquisa", "Produto", FormMethod.Get))
{
    <div class="form-group form-inline">
        <input class="form-control form" type="text" name="nome" id="nome" placeholder="Pesquisar por nome" />
        <input type="submit" value="Pesquisar" class="btn btn-sm btn-default" />
    </div>
}

DesafioIdealeware/DesafioIdealeware/Areas/Admin/Views/Shared/_FormProduto.cshtml
@{ 
    @model DesafioIdealeware.Models.Produto
}

@Html.AntiForgeryToken()

<div class="form-group">
    @Html.LabelFor(p => p.Nome, "Nome:")
    @Html.TextBoxFor(p => p.Nome, new { @class = "form-control" })
    @Html.ValidationMessageFor(p => p.Nome)
</div>

<div class="form-group">
    @Html.LabelFor(p => p.Preco, "Preço: R$")
    @Html.TextBoxFor(p => p.Preco, new { @class = "form-control" })
    @Html.ValidationMessageFor(p => p.Preco)
</div>

<div class="form-group">
    @Html.LabelFor(p => p.Estoque, "Quantidade em Estoque:")
    @Html.TextBoxFor(p => p.Estoque, new { @class = "form-control", @type = "number", @min = "0", @step = "1" })
    @Html.ValidationMessageFor(p => p.Estoque)

</div>

<div class="form-group">
    @Html.LabelFor(p => p.Descricao, "Descricao:")
    @Html.TextAreaFor(p => p.Descricao, new { @class = "form-control" })
    @Html.ValidationMessageFor(p => p.Descricao)
</div>

DesafioIdealeware/DesafioIdealeware/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>    
    @Styles.Render("~/bundles/estilos")
</head>
<body>
    
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Projeto Desafio</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @if (Session["logado"] != null)
                    {
                        <li>@Html.ActionLink("Produtos Cadastrados", "Index", "Produto")</li>
                        <li>@Html.ActionLink("Cadastrar Novo Produto", "Cadastro", "Produto")</li>
                        <li>@Html.ActionLink("Sair", "Logout", "Usuario")</li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row main-area">
                @RenderBody()
        </div>
    </div>

@RenderSection("Scripts", false)
</body>
</html>

DesafioIdealeware/DesafioIdealeware/Areas/Admin/Views/Shared/_ListaProdutos.cshtml
<ul class="list-group">
    @foreach (DesafioIdealeware.Models.Produto item in Model)
    {
        <li class="list-group-item" id="item_@item.Id">
            @Html.ActionLink(item.Nome, "Visualizar", new { id = item.Id })
            <span class="pull-right">
                <a href="#" class="" onclick="apagarProduto(@item.Id)">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </a>
            </span>
        </li>

    }
</ul>

<script type="text/javascript">

    function apagarProduto(produtoId) {

        // TODO: Implementar o Dialog do Bootstrap
        if (confirm("Deseja apagar este produto?")) {
            
            var url = "@Url.Action("Excluir", "Produto")";
            $.post(url, { id: produtoId }, removerLinha(produtoId))

        }
    }

    function removerLinha(id) {
        $("#item_" + id).remove();
    }

</script>

DesafioIdealeware/DesafioIdealeware/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html ng-app="Desafio">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Projeto Desafio</title>
    @Styles.Render("~/bundles/estilospublica")
</head>
<body>
    <div class="container main" ng-controller="produtoController"> 
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">
                        Projeto Desafio
                    </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/Admin">Área Administrativa</a></li>
                     </ul>
                </div>
            </div>
        </nav>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="form-group">
                    <form class="form-inline">
                        <label for="buscar" class="control-label">Localizar produto:</label>
                        <input type="text" name="buscar" id="buscar" placeholder="Pesquisar..." class="form-control" ng-model="produtoSearchStr" />
                    </form>
                </div>
            </div>
            
        </div>

        <div class="row">
            <div class="col-md-4 col-lg-4 col-sm-12" ng-repeat="produto in produtos | filter:produtoSearchStr">
                <div class="panel panel-default">
                    <div class="panel-heading">{{produto.nome}}</div>
                    <div class="panel-body">
                        <p>{{produto.descricao}}</p>
                        <p><strong>Preço:</strong> {{produto.preco | number:2}}</p>
                        <p><strong>Quantidade em estoque:</strong> {{produto.estoque}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    @Scripts.Render("~/bundles/scriptspublica")

</body>
</html>